# Generated by Django 4.1.2 on 2022-10-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WineShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='wine',
            name='name',
            field=models.CharField(max_length=10000),
        ),
    ]
